# Generated by Django 4.2.29 on 2026-04-05 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_worker_api_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('completed', '已完成'), ('canceled', '已取消')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='zone',
            name='status',
            field=models.CharField(choices=[('scheduled', '已安排'), ('working', '进行中'), ('done', '已完成'), ('canceled', '已取消'), ('delayed', '已延期')], default='scheduled', max_length=20),
        ),
        migrations.CreateModel(
            name='WaterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('approved', '已批准'), ('rejected', '已拒绝'), ('info_needed', '需补充信息')], default='submitted', max_length=20)),
                ('status_notes', models.TextField(blank=True, help_text='管理员处理备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_type', models.CharField(choices=[('ENT', 'ENT'), ('FAM', 'FAM'), ('FES', 'FES'), ('其他', '其他')], default='ENT', max_length=20)),
                ('user_type_other', models.CharField(blank=True, help_text='其他用户类型', max_length=50)),
                ('request_type', models.CharField(choices=[('停水需求', '停水需求'), ('新苗程序', '新苗程序'), ('减小水量', '减小水量'), ('加大水量', '加大水量'), ('其他需求', '其他需求')], default='停水需求', max_length=20)),
                ('request_type_other', models.CharField(blank=True, help_text='其他需求类别', max_length=50)),
                ('start_datetime', models.DateTimeField(help_text='需求起始时间')),
                ('end_datetime', models.DateTimeField(help_text='需求结束时间')),
                ('photos', models.JSONField(default=list, help_text='照片URL列表')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_requests', to='core.worker')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zone')),
            ],
            options={
                'db_table': 'water_requests',
            },
        ),
        migrations.CreateModel(
            name='ProjectSupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('approved', '已批准'), ('rejected', '已拒绝'), ('info_needed', '需补充信息')], default='submitted', max_length=20)),
                ('status_notes', models.TextField(blank=True, help_text='管理员处理备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('participants', models.CharField(help_text='参与人员，逗号分隔', max_length=255)),
                ('work_content', models.TextField(help_text='工作内容')),
                ('materials', models.TextField(blank=True, help_text='材料损耗')),
                ('feedback', models.TextField(blank=True, help_text='问题反馈')),
                ('photos', models.JSONField(default=list, help_text='照片URL列表')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_support_requests', to='core.worker')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zone')),
            ],
            options={
                'db_table': 'project_support_requests',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('approved', '已批准'), ('rejected', '已拒绝'), ('info_needed', '需补充信息')], default='submitted', max_length=20)),
                ('status_notes', models.TextField(blank=True, help_text='管理员处理备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('participants', models.CharField(help_text='参与人员，逗号分隔', max_length=255)),
                ('work_content', models.TextField(help_text='工作内容')),
                ('materials', models.TextField(blank=True, help_text='材料损耗')),
                ('feedback', models.TextField(blank=True, help_text='问题反馈')),
                ('photos', models.JSONField(default=list, help_text='照片URL列表')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='core.worker')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zone')),
            ],
            options={
                'db_table': 'maintenance_requests',
            },
        ),
    ]
