# Generated by Django 4.2.29 on 2026-04-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_workorder_status_alter_zone_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='boundary_color',
            field=models.CharField(default='#52B788', help_text='边界颜色 (十六进制)', max_length=7),
        ),
    ]
