# Generated by Django 4.2.29 on 2026-04-06 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_weatherdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='scheduled_end',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='scheduled_start',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='status',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='status_reason',
        ),
    ]
