# Generated by Django 4.2.29 on 2026-04-06 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_maintenancerequest_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='approver',
            field=models.ForeignKey(blank=True, help_text='审批人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to='core.worker'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='审批时间', null=True),
        ),
        migrations.AddField(
            model_name='projectsupportrequest',
            name='approver',
            field=models.ForeignKey(blank=True, help_text='审批人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to='core.worker'),
        ),
        migrations.AddField(
            model_name='projectsupportrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='审批时间', null=True),
        ),
        migrations.AddField(
            model_name='waterrequest',
            name='approver',
            field=models.ForeignKey(blank=True, help_text='审批人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to='core.worker'),
        ),
        migrations.AddField(
            model_name='waterrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='审批时间', null=True),
        ),
    ]
