# Generated by Django 4.2.29 on 2026-04-06 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_maintenancerequest_approver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='department',
            field=models.CharField(blank=True, choices=[('FES', 'FES'), ('FAM', 'FAM'), ('ENT', 'ENT'), ('其他', '其他')], max_length=20),
        ),
        migrations.AddField(
            model_name='worker',
            name='department_other',
            field=models.CharField(blank=True, help_text='其他部门名称', max_length=50),
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('department', models.CharField(choices=[('FES', 'FES'), ('FAM', 'FAM'), ('ENT', 'ENT'), ('其他', '其他')], max_length=20)),
                ('department_other', models.CharField(blank=True, help_text='其他部门名称', max_length=50)),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20)),
                ('status_notes', models.TextField(blank=True, help_text='审批备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_worker', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_request', to='core.worker')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_registrations', to='core.worker')),
            ],
        ),
    ]
