# Generated by Django 4.2.29 on 2026-04-07 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_managerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(choices=[('FES', 'FES'), ('FAM', 'FAM'), ('ENT', 'ENT'), ('其他', '其他')], default='ENT', max_length=20)),
                ('department_other', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '部门用户',
                'verbose_name_plural': '部门用户',
            },
        ),
    ]
