# Generated by Django 4.2.29 on 2026-04-07 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_departmentuserprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationrequest',
            options={'verbose_name': '注册申请', 'verbose_name_plural': '注册申请'},
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='employee_id',
            field=models.CharField(blank=True, help_text='申请时填写的工号，留空则自动生成', max_length=50),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='requested_role',
            field=models.CharField(choices=[('super_admin', '超级管理员'), ('manager', '管理员'), ('field_worker', '现场工作人员'), ('dept_user', '部门用户')], default='field_worker', max_length=20),
        ),
    ]
