# Generated by Django 4.2.29 on 2026-04-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_registrationrequest_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationrequest',
            name='created_worker',
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='password',
            field=models.CharField(blank=True, help_text='登录密码（加密存储）', max_length=128),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='username',
            field=models.CharField(blank=True, help_text='登录用户名', max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='department',
            field=models.CharField(blank=True, choices=[('FES', 'FES'), ('FAM', 'FAM'), ('ENT', 'ENT'), ('其他', '其他')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='employee_id',
            field=models.CharField(blank=True, help_text='工号，审批通过后自动生成', max_length=50),
        ),
    ]
