# Generated by Django 6.0.3 on 2026-04-08 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_registration_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxicomEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(db_index=True, max_length=20)),
                ('source', models.CharField(blank=True, help_text='Event source (S=Site, W=Weather)', max_length=5)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('event_number', models.IntegerField(blank=True, null=True)),
                ('flag', models.CharField(blank=True, help_text='E=Error, W=Warning, I=Info', max_length=5)),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Maxicom事件',
                'verbose_name_plural': 'Maxicom事件',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MaxicomWeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdb_index', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('default_et', models.FloatField(blank=True, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Maxicom气象站',
                'verbose_name_plural': 'Maxicom气象站',
            },
        ),
        migrations.CreateModel(
            name='MaxicomSignalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(db_index=True, max_length=20)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('controller_channel', models.IntegerField(blank=True, null=True)),
                ('signal_index', models.IntegerField(blank=True, null=True)),
                ('signal_table', models.CharField(blank=True, max_length=5)),
                ('signal_type', models.CharField(blank=True, max_length=5)),
                ('signal_value', models.IntegerField(blank=True, null=True)),
                ('signal_multiplier', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Maxicom信号日志',
                'verbose_name_plural': 'Maxicom信号日志',
                'indexes': [models.Index(fields=['timestamp'], name='core_maxico_timesta_4bcfc1_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaxicomSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdb_index', models.IntegerField(help_text='Original IndexNumber from MDB')),
                ('name', models.CharField(max_length=255)),
                ('site_number', models.IntegerField()),
                ('time_zone', models.CharField(default='China', max_length=50)),
                ('water_pricing', models.FloatField(blank=True, null=True)),
                ('ccu_version', models.CharField(blank=True, max_length=50)),
                ('et_current', models.FloatField(blank=True, help_text='Current ET value', null=True)),
                ('et_default', models.FloatField(blank=True, null=True)),
                ('et_minimum', models.FloatField(blank=True, null=True)),
                ('et_maximum', models.FloatField(blank=True, null=True)),
                ('crop_coefficient', models.FloatField(blank=True, null=True)),
                ('rain_shutdown', models.BooleanField(default=False)),
                ('telephone', models.CharField(blank=True, help_text='CCU contact address', max_length=255)),
                ('date_open', models.CharField(blank=True, max_length=20)),
                ('date_close', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maxicom_sites', to='core.zone')),
            ],
            options={
                'verbose_name': 'Maxicom站点',
                'verbose_name_plural': 'Maxicom站点',
                'ordering': ['site_number', 'mdb_index'],
            },
        ),
        migrations.CreateModel(
            name='MaxicomSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdb_index', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('nominal_et', models.FloatField(blank=True, null=True)),
                ('water_budget_factor', models.IntegerField(blank=True, null=True)),
                ('flo_manage', models.BooleanField(default=False)),
                ('send_automatic', models.BooleanField(default=False)),
                ('send_protected', models.BooleanField(default=False)),
                ('instruction_file', models.CharField(blank=True, max_length=255)),
                ('sensitized_et', models.BooleanField(default=False)),
                ('date_open', models.CharField(blank=True, max_length=20)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.maxicomsite')),
            ],
            options={
                'verbose_name': 'Maxicom计划',
                'verbose_name_plural': 'Maxicom计划',
            },
        ),
        migrations.CreateModel(
            name='MaxicomFlowZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdb_index', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('join_site', models.BooleanField(default=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_zones', to='core.maxicomsite')),
            ],
            options={
                'verbose_name': 'Maxicom流量区域',
                'verbose_name_plural': 'Maxicom流量区域',
            },
        ),
        migrations.CreateModel(
            name='MaxicomETCheckbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(db_index=True, max_length=20)),
                ('soil_moisture', models.FloatField(blank=True, null=True)),
                ('rainfall', models.FloatField(blank=True, null=True)),
                ('et', models.FloatField(blank=True, null=True)),
                ('irrigation', models.FloatField(blank=True, null=True)),
                ('soil_moisture_capacity', models.FloatField(blank=True, null=True)),
                ('soil_refill_pct', models.IntegerField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='et_checkbooks', to='core.maxicomsite')),
            ],
            options={
                'verbose_name': 'Maxicom ET账本',
                'verbose_name_plural': 'Maxicom ET账本',
            },
        ),
        migrations.CreateModel(
            name='MaxicomController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdb_index', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('controller_type', models.CharField(blank=True, max_length=255)),
                ('site_number', models.IntegerField()),
                ('link_number', models.IntegerField()),
                ('link_channel', models.IntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('date_open', models.CharField(blank=True, max_length=20)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controllers', to='core.maxicomsite')),
            ],
            options={
                'verbose_name': 'Maxicom控制器',
                'verbose_name_plural': 'Maxicom控制器',
                'ordering': ['site', 'link_number', 'link_channel'],
            },
        ),
        migrations.CreateModel(
            name='MaxicomStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdb_index', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('controller_channel', models.IntegerField()),
                ('precip_rate', models.FloatField(blank=True, help_text='Precipitation rate', null=True)),
                ('flow_rate', models.FloatField(blank=True, help_text='Flow rate', null=True)),
                ('microclimate_factor', models.IntegerField(blank=True, null=True)),
                ('cycle_time', models.IntegerField(blank=True, help_text='Cycle time in minutes', null=True)),
                ('soak_time', models.IntegerField(blank=True, help_text='Soak time in minutes', null=True)),
                ('memo', models.TextField(blank=True)),
                ('lockout', models.BooleanField(default=False)),
                ('flow_manager_priority', models.IntegerField(blank=True, null=True)),
                ('date_open', models.CharField(blank=True, max_length=20)),
                ('controller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='core.maxicomcontroller')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='core.maxicomsite')),
            ],
            options={
                'verbose_name': 'Maxicom灌溉站',
                'verbose_name_plural': 'Maxicom灌溉站',
                'ordering': ['site', 'controller_channel'],
            },
        ),
        migrations.CreateModel(
            name='MaxicomRuntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(db_index=True, max_length=20)),
                ('station_id_raw', models.IntegerField(help_text='Original StationID from MDB')),
                ('run_time', models.IntegerField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runtimes', to='core.maxicomsite')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runtimes', to='core.maxicomstation')),
            ],
            options={
                'verbose_name': 'Maxicom运行时间',
                'verbose_name_plural': 'Maxicom运行时间',
            },
        ),
        migrations.CreateModel(
            name='MaxicomFlowReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(db_index=True, max_length=20)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('multiplier', models.IntegerField(blank=True, null=True)),
                ('site_id', models.IntegerField(blank=True, null=True)),
                ('flow_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.maxicomflowzone')),
            ],
            options={
                'verbose_name': 'Maxicom流量数据',
                'verbose_name_plural': 'Maxicom流量数据',
                'indexes': [models.Index(fields=['flow_zone', 'timestamp'], name='core_maxico_flow_zo_234e03_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaxicomWeatherLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(db_index=True, max_length=20)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('max_temp', models.FloatField(blank=True, null=True)),
                ('min_temp', models.FloatField(blank=True, null=True)),
                ('solar_radiation', models.FloatField(blank=True, null=True)),
                ('rainfall', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('wind_run', models.FloatField(blank=True, null=True)),
                ('et', models.FloatField(blank=True, null=True)),
                ('weather_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.maxicomweatherstation')),
            ],
            options={
                'verbose_name': 'Maxicom气象数据',
                'verbose_name_plural': 'Maxicom气象数据',
                'indexes': [models.Index(fields=['weather_station', 'timestamp'], name='core_maxico_weather_d3a515_idx')],
            },
        ),
    ]
