# Generated by Django 4.2.7 on 2026-04-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_maxicomevent_maxicomweatherstation_maxicomsignallog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncAgentHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('last_sync_counts', models.JSONField(blank=True, default=dict, help_text='Record counts from last sync')),
                ('agent_version', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': '同步代理心跳',
                'verbose_name_plural': '同步代理心跳',
            },
        ),
    ]
