# Generated by Django 4.2.29 on 2026-04-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0015_add_sync_agent_heartbeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('sprinkler', '灌水器类型'), ('solenoid_valve', '电磁阀'), ('isolation_valve', '隔离阀'), ('end_flush_valve', '末端冲洗阀'), ('surface_flush_valve', '地面冲洗阀')], max_length=50)),
                ('model_name', models.CharField(help_text='Equipment model name', max_length=255)),
                ('manufacturer', models.CharField(blank=True, help_text='Manufacturer/brand', max_length=255)),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Type-specific specifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipment Catalog',
                'verbose_name_plural': 'Equipment Catalog',
                'ordering': ['equipment_type', 'manufacturer', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='ZoneEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Number of this equipment in the zone')),
                ('installation_date', models.DateField(blank=True, help_text='Installation date', null=True)),
                ('status', models.CharField(choices=[('working', '正常工作'), ('needs_repair', '需要维修'), ('replaced', '已更换'), ('inactive', '未使用')], default='working', max_length=20)),
                ('location_in_zone', models.CharField(blank=True, help_text='Specific location within zone', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or maintenance history')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zone_installations', to='core.equipmentcatalog')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='core.zone')),
            ],
            options={
                'verbose_name': 'Zone Equipment',
                'verbose_name_plural': 'Zone Equipment',
                'ordering': ['equipment__equipment_type', 'id'],
            },
        ),
    ]
