# Generated by Django 5.2.13 on 2026-04-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_equipment_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentcatalog',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Type-specific specifications (flow rate, pressure, size, etc.)'),
        ),
    ]
