# Generated by Django 4.2.29 on 2026-04-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_equipmentcatalog_specifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('pipeline_type', models.CharField(choices=[('irrigation', '灌溉水管'), ('flush', '冲洗水管')], default='irrigation', help_text='水管类型：灌溉水管或冲洗水管', max_length=20)),
                ('line_points', models.JSONField(default=list, help_text='Array of {lat, lng} points defining the pipeline polyline')),
                ('line_weight', models.IntegerField(default=3, help_text='Line thickness in pixels')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zones', models.ManyToManyField(blank=True, related_name='pipelines', to='core.zone')),
            ],
        ),
    ]
