# Generated by Django 4.2.29 on 2026-04-21 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_pipeline_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zh', models.CharField(max_length=200, verbose_name='中文名称')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='英文名称')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '故障大类',
                'verbose_name_plural': '故障大类',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FaultSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zh', models.CharField(max_length=200, verbose_name='中文名称')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='英文名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='编号')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='core.faultcategory', verbose_name='所属大类')),
            ],
            options={
                'verbose_name': '故障子类型',
                'verbose_name_plural': '故障子类型',
                'ordering': ['category__order', 'category__id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InfoSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='编号')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '信息来源',
                'verbose_name_plural': '信息来源',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='编号')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '位置/CCU',
                'verbose_name_plural': '位置/CCU',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='编号')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '工作分类',
                'verbose_name_plural': '工作分类',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('weather', models.CharField(blank=True, max_length=50, verbose_name='天气')),
                ('zone_location', models.CharField(blank=True, help_text='如 9-4-3、POC、WD 等', max_length=255, verbose_name='故障/事件位置')),
                ('remark', models.TextField(verbose_name='备注/工作内容')),
                ('is_difficult', models.BooleanField(default=False, verbose_name='疑难问题')),
                ('is_difficult_resolved', models.BooleanField(default=False, verbose_name='疑难问题已处理')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '维修工作日报',
                'verbose_name_plural': '维修工作日报',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkReportFault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='数量')),
                ('fault_subtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_entries', to='core.faultsubtype')),
                ('work_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fault_entries', to='core.workreport')),
            ],
            options={
                'verbose_name': '故障计数',
                'verbose_name_plural': '故障计数',
                'unique_together': {('work_report', 'fault_subtype')},
            },
        ),
        migrations.AddField(
            model_name='workreport',
            name='fault_subtypes',
            field=models.ManyToManyField(blank=True, related_name='work_reports', through='core.WorkReportFault', to='core.faultsubtype'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='info_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_reports', to='core.infosource', verbose_name='信息来源'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_reports', to='core.location', verbose_name='位置/CCU'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='work_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_reports', to='core.workcategory', verbose_name='工作分类'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_reports', to='core.worker', verbose_name='处理人'),
        ),
    ]
