# Generated by Django 4.2.29 on 2026-04-22 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_seed_work_report_dicts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workreport',
            name='zone_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_reports', to='core.zone', verbose_name='故障/事件位置'),
        ),
    ]
