# Generated by Django 4.2.29 on 2026-04-22 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_workreport_zone_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='编号')),
                ('category_type', models.CharField(choices=[('global_event', '全局事件'), ('zone_demand', '区域需求'), ('work_category', '工作类别')], max_length=20, verbose_name='类别类型')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '需求类别',
                'verbose_name_plural': '需求类别',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DemandDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='部门名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='部门编号')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '需求部门',
                'verbose_name_plural': '需求部门',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DemandRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='需求日期')),
                ('content', models.TextField(verbose_name='需求内容/备注')),
                ('original_text', models.TextField(blank=True, help_text='Excel原始单元格内容', verbose_name='原始文本')),
                ('demand_department_text', models.CharField(blank=True, max_length=50, verbose_name='提出部门(文本)')),
                ('demand_contact', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('zone_text', models.CharField(blank=True, help_text='Excel行标签', max_length=100, verbose_name='区域(文本)')),
                ('is_global_event', models.BooleanField(default=False, verbose_name='全局事件')),
                ('category_text', models.CharField(blank=True, max_length=100, verbose_name='类别(文本)')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='结束时间')),
                ('crosses_midnight', models.BooleanField(default=False, help_text='结束时间是否跨过午夜', verbose_name='跨天')),
                ('time_parsed', models.BooleanField(default=False, verbose_name='时间已解析')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('approved', '已批准'), ('rejected', '已拒绝'), ('in_progress', '进行中'), ('completed', '已完成'), ('info_needed', '需补充信息')], default='approved', max_length=20, verbose_name='状态')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('status_notes', models.TextField(blank=True, verbose_name='审批备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_zones', models.ManyToManyField(blank=True, related_name='affected_by_demands', to='core.zone', verbose_name='影响区域')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_demands', to='core.worker', verbose_name='审批人')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_records', to='core.demandcategory', verbose_name='需求类别')),
                ('demand_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_records', to='core.demanddepartment', verbose_name='提出部门')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_demands', to='core.worker', verbose_name='提交人')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_demand', to='core.workorder', verbose_name='关联工单')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_records', to='core.zone', verbose_name='关联区域')),
            ],
            options={
                'verbose_name': '需求记录',
                'verbose_name_plural': '需求记录',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['date', 'zone'], name='core_demand_date_93001b_idx'), models.Index(fields=['date', 'category'], name='core_demand_date_7e5e16_idx')],
            },
        ),
    ]
