# Generated by Django 4.2.29 on 2026-04-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_demand_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandrecord',
            name='category_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='类别(文本)'),
        ),
        migrations.AlterField(
            model_name='demandrecord',
            name='zone_text',
            field=models.CharField(blank=True, help_text='Excel行标签', max_length=100, null=True, verbose_name='区域(文本)'),
        ),
    ]
