# Generated by Django 4.2.29 on 2026-04-22 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_fix_demand_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreportfault',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fault_entries', to='core.zoneequipment', verbose_name='故障设备'),
        ),
    ]
