# Generated by Django 4.2.29 on 2026-04-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_equipment_to_work_report_fault'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'verbose_name': '植物', 'verbose_name_plural': '植物'},
        ),
        migrations.AddField(
            model_name='plant',
            name='planting_date',
            field=models.DateField(blank=True, null=True, verbose_name='种植日期'),
        ),
    ]
