# Generated by Django 4.2.29 on 2026-04-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_planting_date_to_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='planting_date',
            field=models.DateField(blank=True, null=True, verbose_name='开始日期'),
        ),
    ]
