# Generated by Django 4.2.29 on 2026-04-22 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_plant_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='片区名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='片区编号')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '片区',
                'verbose_name_plural': '片区',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='zone',
            name='patch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones', to='core.patch', verbose_name='所属片区'),
        ),
    ]
