# Generated by Django 5.2.13 on 2026-04-23 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_add_photos_to_workreport'),
    ]

    operations = [
    ]
