# Generated by Django 6.0.3 on 2026-04-25 09:32

import django.db.models.deletion
from django.db import migrations, models


def migrate_data_to_patch(apps, schema_editor):
    """Convert existing Location, MaxicomSite, MaxicomStation records to Patch."""
    Patch = apps.get_model('core', 'Patch')
    Location = apps.get_model('core', 'Location')
    MaxicomSite = apps.get_model('core', 'MaxicomSite')
    MaxicomStation = apps.get_model('core', 'MaxicomStation')
    DemandRecord = apps.get_model('core', 'DemandRecord')
    Zone = apps.get_model('core', 'Zone')
    WorkReport = apps.get_model('core', 'WorkReport')
    MaxicomSchedule = apps.get_model('core', 'MaxicomSchedule')
    MaxicomFlowZone = apps.get_model('core', 'MaxicomFlowZone')
    MaxicomETCheckbook = apps.get_model('core', 'MaxicomETCheckbook')
    MaxicomRuntime = apps.get_model('core', 'MaxicomRuntime')
    MaxicomController = apps.get_model('core', 'MaxicomController')

    # 1. Migrate Location -> Patch (type='location')
    location_id_map = {}
    for loc in Location.objects.all():
        p = Patch.objects.create(
            name=loc.name, code=loc.code, description='',
            type='location', order=loc.order, active=loc.active,
            created_at=loc.created_at, updated_at=loc.updated_at,
        )
        location_id_map[loc.id] = p.id

    # 2. Migrate MaxicomSite -> Patch (type='site')
    site_id_map = {}
    for s in MaxicomSite.objects.all():
        p = Patch.objects.create(
            name=s.name, code='site-{}'.format(s.mdb_index), description='',
            type='site', mdb_index=s.mdb_index, site_number=s.site_number,
            time_zone=s.time_zone, water_pricing=s.water_pricing,
            ccu_version=s.ccu_version, et_current=s.et_current,
            et_default=s.et_default, et_minimum=s.et_minimum,
            et_maximum=s.et_maximum, crop_coefficient=s.crop_coefficient,
            rain_shutdown=s.rain_shutdown, telephone=s.telephone,
            date_open=s.date_open, date_close=s.date_close,
            active=True,
        )
        site_id_map[s.id] = p.id

    # 3. Migrate MaxicomStation -> Patch (type='station')
    station_id_map = {}
    for stn in MaxicomStation.objects.all():
        parent_patch_id = site_id_map.get(stn.site_id)
        stn_name = stn.name if stn.name else 'Station-{}'.format(stn.mdb_index)
        p = Patch.objects.create(
            name=stn_name, code='station-{}'.format(stn.mdb_index),
            description=stn.memo, type='station', parent_id=parent_patch_id,
            mdb_index=stn.mdb_index,
            controller_channel=stn.controller_channel,
            precip_rate=stn.precip_rate, flow_rate=stn.flow_rate,
            microclimate_factor=stn.microclimate_factor,
            cycle_time=stn.cycle_time, soak_time=stn.soak_time,
            lockout=stn.lockout, flow_manager_priority=stn.flow_manager_priority,
            date_open=stn.date_open, active=True,
        )
        station_id_map[stn.id] = p.id

    # 4. Create Patch records from DemandRecord.zone_text distinct values
    zone_texts_raw = DemandRecord.objects.exclude(zone_text__isnull=True).exclude(
        zone_text=''
    ).values_list('zone_text', flat=True).distinct()
    zone_texts = sorted(set(zone_texts_raw))
    for i, zt in enumerate(zone_texts):
        # Skip if a Patch with this name already exists
        if Patch.objects.filter(name=zt).exists():
            continue
        Patch.objects.create(
            name=zt, code='zt-{:05d}'.format(i), description='Zone text: ' + zt,
            type='zone_text', active=True,
        )

    # 5. Match zone_text values to Zone.code — set Zone.patch FK
    for zt in zone_texts:
        zone = Zone.objects.filter(code=zt).first()
        if zone:
            patch = Patch.objects.filter(type='zone_text', name=zt).first()
            if patch:
                zone.patch = patch
                zone.save(update_fields=['patch'])

    # 6. Relink WorkReport.location_id -> new Patch (type='location')
    for wr in WorkReport.objects.select_related('location').all():
        new_patch_id = location_id_map.get(wr.location_id)
        if new_patch_id:
            WorkReport.objects.filter(pk=wr.pk).update(location_id=new_patch_id)

    # 7. Relink MaxicomSchedule.site_id -> new Patch
    for sched in MaxicomSchedule.objects.all():
        new_patch_id = site_id_map.get(sched.site_id)
        if new_patch_id:
            MaxicomSchedule.objects.filter(pk=sched.pk).update(site_id=new_patch_id)

    # 8. Relink MaxicomFlowZone.site_id -> new Patch
    for fz in MaxicomFlowZone.objects.all():
        new_patch_id = site_id_map.get(fz.site_id)
        if new_patch_id:
            MaxicomFlowZone.objects.filter(pk=fz.pk).update(site_id=new_patch_id)

    # 9. Relink MaxicomETCheckbook.site_id -> new Patch
    for et in MaxicomETCheckbook.objects.all():
        new_patch_id = site_id_map.get(et.site_id)
        if new_patch_id:
            MaxicomETCheckbook.objects.filter(pk=et.pk).update(site_id=new_patch_id)

    # 10. Relink MaxicomRuntime.site_id -> new Patch
    for rt in MaxicomRuntime.objects.all():
        new_patch_id = site_id_map.get(rt.site_id)
        if new_patch_id:
            MaxicomRuntime.objects.filter(pk=rt.pk).update(site_id=new_patch_id)

    # 11. Relink MaxicomRuntime.station_id -> new Patch
    for rt in MaxicomRuntime.objects.all():
        new_patch_id = station_id_map.get(rt.station_id)
        if new_patch_id:
            MaxicomRuntime.objects.filter(pk=rt.pk).update(station_id=new_patch_id)

    # 12. Relink MaxicomController.site_id -> new Patch
    for ctrl in MaxicomController.objects.all():
        new_patch_id = site_id_map.get(ctrl.site_id)
        if new_patch_id:
            MaxicomController.objects.filter(pk=ctrl.pk).update(site_id=new_patch_id)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_add_api_token_to_manager_and_dept'),
    ]

    operations = [
        # Step 1: Add all new fields to Patch first
        migrations.AlterModelOptions(
            name='patch',
            options={'ordering': ['type', 'code'], 'verbose_name': '区域', 'verbose_name_plural': '区域'},
        ),
        migrations.AddField(
            model_name='patch',
            name='active',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AddField(
            model_name='patch',
            name='ccu_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patch',
            name='controller_channel',
            field=models.IntegerField(blank=True, null=True, verbose_name='控制器通道'),
        ),
        migrations.AddField(
            model_name='patch',
            name='crop_coefficient',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patch',
            name='cycle_time',
            field=models.IntegerField(blank=True, help_text='Cycle time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='patch',
            name='date_close',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patch',
            name='date_open',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patch',
            name='et_current',
            field=models.FloatField(blank=True, help_text='Current ET value', null=True),
        ),
        migrations.AddField(
            model_name='patch',
            name='et_default',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patch',
            name='et_maximum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patch',
            name='et_minimum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patch',
            name='flow_manager_priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patch',
            name='flow_rate',
            field=models.FloatField(blank=True, help_text='Flow rate', null=True),
        ),
        migrations.AddField(
            model_name='patch',
            name='lockout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patch',
            name='mdb_index',
            field=models.IntegerField(blank=True, help_text='Original IndexNumber from MDB', null=True, verbose_name='Maxicom索引'),
        ),
        migrations.AddField(
            model_name='patch',
            name='microclimate_factor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patch',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='patch',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.patch', verbose_name='上级'),
        ),
        migrations.AddField(
            model_name='patch',
            name='precip_rate',
            field=models.FloatField(blank=True, help_text='Precipitation rate', null=True),
        ),
        migrations.AddField(
            model_name='patch',
            name='rain_shutdown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patch',
            name='site_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='站点编号'),
        ),
        migrations.AddField(
            model_name='patch',
            name='soak_time',
            field=models.IntegerField(blank=True, help_text='Soak time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='patch',
            name='telephone',
            field=models.CharField(blank=True, help_text='CCU contact address', max_length=255),
        ),
        migrations.AddField(
            model_name='patch',
            name='time_zone',
            field=models.CharField(blank=True, default='China', max_length=50),
        ),
        migrations.AddField(
            model_name='patch',
            name='type',
            field=models.CharField(choices=[('patch', '片区'), ('site', 'Maxicom站点'), ('station', 'Maxicom灌溉站'), ('location', '位置/CCU'), ('zone_text', '需求区域')], default='patch', max_length=20),
        ),
        migrations.AddField(
            model_name='patch',
            name='water_pricing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patch',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='patch',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),

        # Step 2: Convert existing records to Patch (data migration)
        migrations.RunPython(migrate_data_to_patch, migrations.RunPython.noop),

        # Step 3: Alter FK fields to point to Patch
        migrations.AlterField(
            model_name='workreport',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_reports', to='core.patch', verbose_name='位置/CCU'),
        ),
        migrations.RemoveField(
            model_name='maxicomsite',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='maxicomstation',
            name='site',
        ),
        migrations.AlterField(
            model_name='maxicomcontroller',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controllers', to='core.patch'),
        ),
        migrations.AlterField(
            model_name='maxicomflowzone',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_zones', to='core.patch'),
        ),
        migrations.AlterField(
            model_name='maxicomschedule',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.patch'),
        ),
        migrations.AlterField(
            model_name='maxicomruntime',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runtime_as_site', to='core.patch'),
        ),
        migrations.AlterField(
            model_name='maxicometcheckbook',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='et_checkbooks', to='core.patch'),
        ),
        migrations.RemoveField(
            model_name='maxicomstation',
            name='controller',
        ),
        migrations.AlterField(
            model_name='maxicomruntime',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runtime_as_station', to='core.patch'),
        ),

        # Step 4: Delete old models
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='MaxicomSite',
        ),
        migrations.DeleteModel(
            name='MaxicomStation',
        ),
    ]
