# Generated by Django 5.2.13 on 2026-04-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_workreport_location_remove_maxicomsite_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='priority',
            field=models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='优先级'),
        ),
    ]
