# Generated by Django 6.0.3 on 2026-05-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_zone_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='label_angle',
            field=models.IntegerField(default=0, help_text='Label rotation in degrees'),
        ),
        migrations.AddField(
            model_name='zone',
            name='label_lat',
            field=models.FloatField(blank=True, help_text='Custom label latitude override', null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='label_lng',
            field=models.FloatField(blank=True, help_text='Custom label longitude override', null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='label_scale',
            field=models.FloatField(default=1.0, help_text='Label font size multiplier'),
        ),
    ]
