# Generated by Django 5.2.13 on 2026-04-30 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_region_patch_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['order', 'name'], 'verbose_name': '大区', 'verbose_name_plural': '大区'},
        ),
        migrations.RemoveField(
            model_name='region',
            name='code',
        ),
    ]
