# Generated by Django 6.0.3 on 2026-05-12 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_zone_label_settings'),
        ('core', '0034_remove_region_code'),
    ]

    operations = [
    ]
