# Generated by Django 6.0.3 on 2026-05-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_merge_20260512_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='area_sqm',
            field=models.FloatField(blank=True, help_text='Calculated area in square meters', null=True),
        ),
    ]
