# Generated by Django 6.0.3 on 2026-05-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_zone_name_not_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patch',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
