# Generated by Django 6.0.3 on 2026-05-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_patch_name_not_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patch',
            options={'ordering': ['code'], 'verbose_name': '区域', 'verbose_name_plural': '区域'},
        ),
        migrations.RemoveField(
            model_name='patch',
            name='type',
        ),
    ]
