# Generated by Django 6.0.3 on 2026-05-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_patch_type_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='current_status',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='当前状态'),
        ),
        migrations.AddField(
            model_name='zone',
            name='equipment_maintenance_notes',
            field=models.TextField(blank=True, default='', verbose_name='灌溉设备维护记录'),
        ),
        migrations.AddField(
            model_name='zone',
            name='greenery_foreman',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='绿化领班'),
        ),
        migrations.AddField(
            model_name='zone',
            name='greenery_zone',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='绿化分区'),
        ),
        migrations.AddField(
            model_name='zone',
            name='irrigation_foreman',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='灌溉领班'),
        ),
        migrations.AddField(
            model_name='zone',
            name='irrigation_intensity',
            field=models.FloatField(blank=True, null=True, verbose_name='灌溉强度(mm/h)'),
        ),
        migrations.AddField(
            model_name='zone',
            name='irrigation_management_notes',
            field=models.TextField(blank=True, default='', verbose_name='灌溉管理记录'),
        ),
        migrations.AddField(
            model_name='zone',
            name='landscape_coefficient',
            field=models.FloatField(blank=True, null=True, verbose_name='景观系数'),
        ),
        migrations.AddField(
            model_name='zone',
            name='pest_control_foreman',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='植保领班'),
        ),
        migrations.AddField(
            model_name='zone',
            name='pest_control_zone',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='植保分区'),
        ),
        migrations.AddField(
            model_name='zone',
            name='plant_feature',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='植物特点'),
        ),
        migrations.AddField(
            model_name='zone',
            name='plant_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='植物类型'),
        ),
        migrations.AddField(
            model_name='zone',
            name='soil_moisture',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='土壤湿度'),
        ),
        migrations.AddField(
            model_name='zone',
            name='solenoid_valve_size',
            field=models.FloatField(blank=True, null=True, verbose_name='电磁阀尺寸'),
        ),
        migrations.AddField(
            model_name='zone',
            name='sprinkler_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='灌水器类型'),
        ),
        migrations.AddField(
            model_name='zone',
            name='terrain_feature',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='地形特点'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='priority',
            field=models.CharField(choices=[('critical', '超级重点'), ('high', '重点'), ('medium', '一般'), ('low', '次要'), ('abolished', '废除')], default='medium', max_length=10, verbose_name='优先级'),
        ),
    ]
