# Generated by Django 6.0.3 on 2026-05-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_zone_current_status_zone_equipment_maintenance_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='User preferences JSON (card fields, etc.)'),
        ),
    ]
