# Generated by Django 6.0.3 on 2026-05-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_managerprofile_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='confirmed_remarks',
            field=models.TextField(blank=True, default='', verbose_name='备注确认'),
        ),
        migrations.AddField(
            model_name='zone',
            name='remarks',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
    ]
