# Generated by Django 4.2.29 on 2026-05-16 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_zone_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名称')),
                ('boundary_points', models.JSONField(default=list, verbose_name='边界坐标')),
                ('boundary_color', models.CharField(default='#E8590C', max_length=7, verbose_name='边界颜色')),
                ('center', models.JSONField(blank=True, null=True, verbose_name='中心点')),
                ('area_sqm', models.FloatField(blank=True, null=True, verbose_name='面积(m²)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '地标',
                'verbose_name_plural': '地标',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ZoneLandmarkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_assignments', to='core.landmark')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmark_assignments', to='core.zone')),
            ],
            options={
                'unique_together': {('zone', 'landmark')},
            },
        ),
    ]
