# Generated by Django 4.2.29 on 2026-05-19 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0043_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='drawn_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawn_zones', to=settings.AUTH_USER_MODEL, verbose_name='绘制人'),
        ),
    ]
