# Generated by Django 4.2.29 on 2026-05-21 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0044_zone_drawn_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrequest',
            name='requested_role',
            field=models.CharField(choices=[('super_admin', '超级管理员'), ('manager', '管理员'), ('field_worker', '灌溉一线'), ('dept_user', '部门用户')], default='field_worker', max_length=20),
        ),
        migrations.CreateModel(
            name='MapStyleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '地图样式',
                'verbose_name_plural': '地图样式',
            },
        ),
    ]
