# Generated by Django 4.2.29 on 2026-05-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_mapstylesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='smooth_override',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Per-zone boundary smooth override (null=follow global, 0-3=custom)', null=True),
        ),
    ]
