# Generated by Django 5.2.14 on 2026-05-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_zone_smooth_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='ring_display_modes',
            field=models.JSONField(blank=True, default=dict, help_text='Per-ring display mode: {"0":"sublabel"}. Missing keys default to "line".'),
        ),
    ]
