# Generated by Django 5.2.14 on 2026-06-03 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_zone_ring_display_modes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.workcategory', verbose_name='父级分类'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='shift',
            field=models.CharField(blank=True, choices=[('早班', '早班'), ('白班', '白班'), ('夜班', '夜班')], max_length=10, verbose_name='班次'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='team_hours',
            field=models.FloatField(default=0, help_text='Auto-calculated, precision 0.5h', verbose_name='灌溉组工时'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='team_size',
            field=models.PositiveIntegerField(default=1, verbose_name='灌溉组人数'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='third_party_count',
            field=models.PositiveIntegerField(default=0, verbose_name='第三方人数'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='third_party_hours',
            field=models.FloatField(default=0, help_text='Auto-calculated, precision 0.5h', verbose_name='第三方工时'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='work_content',
            field=models.TextField(blank=True, verbose_name='工作内容'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='work_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='工作完成时间'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='work_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='工作开始时间'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='zone_names',
            field=models.TextField(blank=True, help_text='Auto-filled from zone codes', verbose_name='通称位置'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='zones',
            field=models.ManyToManyField(blank=True, related_name='workorder_records', to='core.zone', verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='remark',
            field=models.TextField(blank=True, verbose_name='备注/工作内容'),
        ),
    ]
