# Generated by Django 6.0.3 on 2026-06-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_workcategory_parent_workreport_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='boundary_source',
            field=models.CharField(choices=[('manual', '手动绘制'), ('dxf', 'DXF导入')], default='manual', help_text='当前生效的边界来源', max_length=10),
        ),
        migrations.AddField(
            model_name='zone',
            name='dxf_boundary_points',
            field=models.JSONField(blank=True, default=list, help_text='DXF导入的边界'),
        ),
        migrations.AddField(
            model_name='zone',
            name='dxf_boundary_source',
            field=models.CharField(blank=True, default='', help_text='DXF来源文件名', max_length=255),
        ),
    ]
