# Generated by Django 6.0.3 on 2026-06-14 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_zone_boundary_source_zone_dxf_boundary_points_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='启用')),
                ('api_base_url', models.CharField(blank=True, default='', help_text='OpenAI 兼容接口地址，如 https://api.deepseek.com/v1', max_length=255, verbose_name='API 地址')),
                ('api_key', models.CharField(blank=True, default='', help_text='服务商提供的密钥（明文存储，请确保数据库访问受控）', max_length=255, verbose_name='API Key')),
                ('model_name', models.CharField(blank=True, default='', help_text='如 deepseek-chat、gpt-4o-mini、qwen-plus 等', max_length=100, verbose_name='模型名称')),
                ('temperature', models.FloatField(default=0.3, help_text='0=严谨确定，1=发散，数据分析建议 0.2~0.4', verbose_name='温度')),
                ('system_prompt', models.TextField(blank=True, default='', help_text='留空则使用默认提示词', verbose_name='系统提示词')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_settings_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI 助手设置',
                'verbose_name_plural': 'AI 助手设置',
            },
        ),
    ]
