# Generated by Django 6.0.3 on 2026-06-15 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_aisettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('category', models.CharField(choices=[('FAM', 'FAM项目'), ('WDI', 'WDI项目'), ('OTHER', '其它')], default='FAM', max_length=20, verbose_name='项目类别')),
                ('code', models.CharField(blank=True, max_length=100, verbose_name='项目代号')),
                ('active', models.BooleanField(default=True, verbose_name='启用')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '灌溉项目',
                'verbose_name_plural': '灌溉项目',
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='文档点号路径，幂等灌入与外部引用键', max_length=100, unique=True, verbose_name='编码')),
                ('name_zh', models.CharField(max_length=255, verbose_name='中文名')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='英文名')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='同级排序')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='层级深度')),
                ('section', models.CharField(choices=[('routine_maint', '常规维护'), ('irrigation_project', '灌溉项目'), ('routine_support', '常规配合'), ('greenhouse_nursery', '温室和苗圃维护'), ('warehouse', '仓库整理'), ('meeting_training', '会议和培训'), ('repair_emergency', '报修应急'), ('other_project', '其他项目'), ('drainage_project', '排水项目'), ('typhoon_emergency', '台风应急'), ('safety_incident', '安全事件记录'), ('good_deed', '优秀事迹记录')], db_index=True, max_length=30, verbose_name='顶层章节')),
                ('value_type', models.CharField(choices=[('group', '分组(无值)'), ('count', '计数'), ('status', '状态选择'), ('text', '纯文本'), ('text_photo', '文本+照片')], default='count', max_length=20, verbose_name='值类型')),
                ('status_options', models.JSONField(blank=True, default=list, help_text='仅 status 型：可选状态列表', verbose_name='状态选项')),
                ('unit', models.CharField(blank=True, help_text='仅 count 型，如 m / 个', max_length=20, verbose_name='单位')),
                ('is_project_scoped', models.BooleanField(default=False, help_text='灌溉项目章节的节点填报时需选 Project', verbose_name='需绑定项目')),
                ('active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.workitem', verbose_name='父节点')),
            ],
            options={
                'verbose_name': '工作内容节点',
                'verbose_name_plural': '工作内容节点',
                'ordering': ['section', 'order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='WorkReportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='数量')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='状态值')),
                ('text_value', models.TextField(blank=True, verbose_name='文本')),
                ('photos', models.JSONField(blank=True, default=list, verbose_name='照片')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='core.project', verbose_name='项目')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='core.workitem', verbose_name='节点')),
                ('work_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.workreport', verbose_name='工单')),
            ],
            options={
                'verbose_name': '工单明细',
                'verbose_name_plural': '工单明细',
                'unique_together': {('work_report', 'work_item', 'project')},
            },
        ),
    ]
