# Generated by Django 5.2.14 on 2026-06-16 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_workorder_template_tree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workreport',
            name='work_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_reports', to='core.workcategory', verbose_name='工作分类'),
        ),
    ]
