# Generated by Django 5.2.14 on 2026-06-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_workreport_work_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('FAM', 'FAM项目'), ('WDI', 'WDI项目'), ('GREEN', '绿化项目')], default='FAM', max_length=20, verbose_name='项目类别'),
        ),
    ]
