# Generated by Django 5.2.14 on 2026-06-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='value_type',
            field=models.CharField(choices=[('group', '分组(无值)'), ('count', '计数'), ('status', '状态选择'), ('toggle', '勾选(无数量)'), ('text', '纯文本'), ('text_photo', '文本+照片')], default='count', max_length=20, verbose_name='值类型'),
        ),
    ]
