# Generated by Django 5.2.14 on 2026-06-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_workitem_value_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['category', 'subcategory', 'name'], 'verbose_name': '灌溉项目', 'verbose_name_plural': '灌溉项目'},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='project',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('FAM', 'FAM项目'), ('FES', 'FES项目'), ('WDI', 'WDI项目'), ('GREEN', '绿化项目')], help_text='仅灌溉项目：FAM/FES/WDI/绿化', max_length=20, verbose_name='子类别'),
        ),
        migrations.AddField(
            model_name='project',
            name='symbol',
            field=models.CharField(blank=True, max_length=50, verbose_name='项目代号'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('IRRIGATION', '灌溉项目'), ('DRAINAGE', '排水项目'), ('OTHER', '其他项目')], default='IRRIGATION', max_length=20, verbose_name='项目类别'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(blank=True, max_length=100, verbose_name='项目Code'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('category', 'subcategory', 'name')},
        ),
    ]
