# Generated by Django 5.2.14 on 2026-06-16 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_project_options_alter_project_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Land',
                'verbose_name_plural': 'Lands',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='zone',
            name='land',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones', to='core.land', verbose_name='所属Land'),
        ),
    ]
