# Generated by Django 5.2.15 — drops legacy models.
# Rewritten to use direct table drops via RunSQL. The auto-generated field-by-field
# removal failed on SQLite because rebuilding DemandRecord's table (to drop the
# `category` column) tripped an index that referenced that same column mid-rebuild.
# Since all dropped data is legacy/disposable, dropping the tables directly is safe.

from django.db import migrations


def drop_legacy_tables_forward(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        # 1. Null out WorkReport FK columns BEFORE dropping the referenced tables, so the
        #    post-migration constraint check passes (SQLite validates FKs at commit time).
        for col in ['work_category_id', 'info_source_id']:
            try:
                cursor.execute(f'UPDATE core_workreport SET {col} = NULL WHERE {col} IS NOT NULL')
            except Exception:
                pass
        # 2. Drop the legacy tables outright.
        for tbl in [
            'core_demandrecord', 'core_demandcategory', 'core_demanddepartment',
            'core_event',
            'core_workreportfault', 'core_faultsubtype', 'core_faultcategory',
            'core_infosource',
            'core_maintenancerequest', 'core_projectsupportrequest',
            'core_workcategory', 'core_worklog', 'core_workorder',
        ]:
            try:
                cursor.execute(f'DROP TABLE IF EXISTS {tbl}')
            except Exception:
                pass
        # 3. Now drop the WorkReport FK columns (the tables they pointed to are gone).
        #    IMPORTANT: SQLite refuses DROP COLUMN if an index references the column,
        #    so drop those indexes first. Index names follow Django's <table>_<col>_<hash>.
        for idx_sql in [
            "SELECT name FROM sqlite_master WHERE type='index' AND tbl_name='core_workreport' "
            "AND (name LIKE 'core_workreport_work_category_%' OR name LIKE 'core_workreport_info_source_%')"
        ]:
            cursor.execute(idx_sql)
            for (idx_name,) in cursor.fetchall():
                try:
                    cursor.execute(f'DROP INDEX IF EXISTS "{idx_name}"')
                except Exception:
                    pass
        for col in ['work_category_id', 'info_source_id']:
            try:
                cursor.execute(f'ALTER TABLE core_workreport DROP COLUMN {col}')
            except Exception:
                pass  # already gone


def drop_legacy_tables_backward(apps, schema_editor):
    # No-op: re-creating legacy tables is not supported (models are removed from code).
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_workreport_resolved_by_pm'),
    ]

    operations = [
        migrations.RunPython(drop_legacy_tables_forward, drop_legacy_tables_backward),
    ]
