# Generated by Django 5.2.15 — additive: WaterRequest.zones M2M + nullable legacy zone.
# (The DeleteModel/RemoveField ops Django auto-generated for the legacy models are
#  omitted here — those tables were already dropped by migration 0059. This migration
#  keeps only the real M2M/nullable change + a data-copy step.)

import django.db.models.deletion
from django.db import migrations, models


def copy_zone_to_zones(apps, schema_editor):
    """Copy each WaterRequest's legacy single `zone` FK into the new `zones` M2M,
    so existing data is preserved on the multi-zone field."""
    WaterRequest = apps.get_model('core', 'WaterRequest')
    for wr in WaterRequest.objects.exclude(zone=None):
        if wr.zone_id and not wr.zones.filter(id=wr.zone_id).exists():
            wr.zones.add(wr.zone_id)


def reverse_copy(apps, schema_editor):
    # No-op reverse (the legacy FK is kept nullable; we don't remove the M2M).
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_remove_demandrecord_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterrequest',
            name='zones',
            field=models.ManyToManyField(blank=True, help_text='该需求涉及的多个区域',
                                          related_name='water_requests', to='core.zone',
                                          verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='waterrequest',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='(Legacy) 主区域，新记录使用 zones M2M',
                                     null=True, on_delete=django.db.models.deletion.CASCADE,
                                     related_name='%(class)s', to='core.zone'),
        ),
        migrations.RunPython(copy_zone_to_zones, reverse_copy),
    ]
