# Generated by Django 4.2.7 on 2026-06-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_remove_demandrecord_affected_zones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='controller_number',
            field=models.IntegerField(blank=True, help_text='StationControllerNumber from MDB — IndexNumber of the satellite controller this valve belongs to', null=True, verbose_name='所属控制器编号'),
        ),
    ]
