# Generated by Django 4.2.7 on 2026-06-25 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_workreport_location_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workreport_comments', to='core.worker', verbose_name='评论人')),
                ('work_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.workreport', verbose_name='工单')),
            ],
            options={
                'verbose_name': '工单评论',
                'verbose_name_plural': '工单评论',
                'ordering': ['created_at'],
            },
        ),
    ]
