# Generated by Django 4.2.28 on 2026-06-29 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkReportEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='编辑时间')),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workreport_edits', to='core.worker', verbose_name='编辑人')),
                ('work_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='core.workreport', verbose_name='工单')),
            ],
            options={
                'verbose_name': '编辑记录',
                'verbose_name_plural': '编辑记录',
                'ordering': ['created_at'],
            },
        ),
    ]
