# Generated by Django 5.2.15 on 2026-06-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_workreporteditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workreport',
            name='date',
            field=models.DateField(db_index=True, verbose_name='日期'),
        ),
        migrations.AddIndex(
            model_name='maxicomruntime',
            index=models.Index(fields=['site', 'timestamp'], name='core_maxico_site_id_73c87c_idx'),
        ),
    ]
