# Generated by Django 4.2.7 on 2026-07-01 15:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_workreport_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='路径派生的稳定编码，幂等灌入键', max_length=200, unique=True, verbose_name='编码')),
                ('name_zh', models.CharField(max_length=255, verbose_name='中文名')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='同级排序')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='层级深度')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, help_text='由经理设定初始值；每次出入库提交后自动增减', max_digits=12, verbose_name='现有库存数量')),
                ('active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.inventorycategory', verbose_name='父节点')),
            ],
            options={
                'verbose_name': '库存物料',
                'verbose_name_plural': '库存物料',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='日期')),
                ('operation', models.CharField(choices=[('入库', '入库'), ('出库', '出库'), ('借用', '借用'), ('归还', '归还')], max_length=10, verbose_name='操作类型')),
                ('order_no', models.CharField(blank=True, help_text='入库时填写', max_length=100, verbose_name='订单号')),
                ('counterparty', models.CharField(blank=True, help_text='出库/借用时填写（日常维护/项目名/借用方）', max_length=200, verbose_name='去向/借用方')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('photos', models.JSONField(blank=True, default=list, verbose_name='照片')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='core.project', verbose_name='关联项目')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='core.worker', verbose_name='提交人')),
                ('zone', models.ForeignKey(blank=True, help_text='可选；与具体区域关联', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='core.zone', verbose_name='关联区域')),
            ],
            options={
                'verbose_name': '库存流水',
                'verbose_name_plural': '库存流水',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransactionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='数量')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='单位')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_lines', to='core.inventorycategory', verbose_name='物料')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.inventorytransaction', verbose_name='流水单')),
            ],
            options={
                'verbose_name': '库存明细',
                'verbose_name_plural': '库存明细',
                'unique_together': {('transaction', 'category')},
            },
        ),
    ]
