# Generated by Django 4.2.7 on 2026-07-01 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='entry_subtype',
            field=models.CharField(blank=True, max_length=20, verbose_name='来源/去向类型'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='counterparty',
            field=models.CharField(blank=True, help_text='出库-借用时填写（历史去重 + 可自填）', max_length=200, verbose_name='借用方'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='operation',
            field=models.CharField(choices=[('入库', '入库'), ('出库', '出库')], max_length=10, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='order_no',
            field=models.CharField(blank=True, help_text='入库-采购时填写', max_length=100, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='related_project',
            field=models.ForeignKey(blank=True, help_text='出库-项目时选择', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='core.project', verbose_name='关联项目'),
        ),
    ]
