# Generated by Django 4.2.7 on 2026-07-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_inventory_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycategory',
            name='current_stock',
            field=models.IntegerField(default=0, help_text='由经理设定初始值；每次出入库提交后自动增减', verbose_name='现有库存数量'),
        ),
        migrations.AlterField(
            model_name='inventorytransactionline',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='数量'),
        ),
    ]
