# Generated by Django 4.2.7 on 2026-07-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_inventory_integer_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycategory',
            name='is_main_material',
            field=models.BooleanField(default=False, help_text='主材在日后管理中着重统计与分析', verbose_name='是否主材'),
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='min_stock',
            field=models.IntegerField(default=0, help_text='由经理设定；低于此值视为库存不足，便于日后预警', verbose_name='最小库存量'),
        ),
    ]
