# Generated by Django 6.0.3 on 2026-07-04 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_purchase_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='计划数量')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='单位')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='core.inventorycategory', verbose_name='物料')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_lines', to='core.purchaseorder', verbose_name='采购订单')),
            ],
            options={
                'verbose_name': '计划采购明细',
                'verbose_name_plural': '计划采购明细',
                'unique_together': {('purchase_order', 'category')},
            },
        ),
    ]
