# Generated by Django 6.0.3 on 2026-07-04 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_purchaseorderline'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='labor_budget_hours',
            field=models.FloatField(blank=True, help_text='经理填写；已用工时由工单自动汇总', null=True, verbose_name='人工预算工时'),
        ),
        migrations.CreateModel(
            name='ProjectMaterialBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='预算数量')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='单位')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_budgets', to='core.inventorycategory', verbose_name='物料')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_budget', to='core.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目材料预算',
                'verbose_name_plural': '项目材料预算',
                'unique_together': {('project', 'category')},
            },
        ),
        migrations.CreateModel(
            name='ProjectPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_links', to='core.project', verbose_name='项目')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='core.purchaseorder', verbose_name='采购订单')),
            ],
            options={
                'verbose_name': '项目-采购订单',
                'verbose_name_plural': '项目-采购订单',
                'unique_together': {('project', 'purchase_order')},
            },
        ),
    ]
