# Generated by Django 6.0.3 on 2026-07-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_project_budget_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='标记项目是否已完工', verbose_name='已完成'),
        ),
    ]
