# Generated by Django 6.0.3 on 2026-07-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_project_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='planned_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='计划完工日期'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='开工日期'),
        ),
    ]
