# Generated by Django 6.0.3 on 2026-07-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_project_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='third_party_budget_hours',
            field=models.FloatField(blank=True, help_text='经理填写；已用工时由工单自动汇总', null=True, verbose_name='第三方预算工时'),
        ),
        migrations.AlterField(
            model_name='project',
            name='labor_budget_hours',
            field=models.FloatField(blank=True, help_text='经理填写；已用工时由工单自动汇总', null=True, verbose_name='第一方预算工时'),
        ),
    ]
