# Generated by Django 6.0.3 on 2026-07-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_project_third_party_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='received_date',
            field=models.DateField(blank=True, help_text='采购订单的收货/到货日期', null=True, verbose_name='收货日期'),
        ),
    ]
