# Generated by Django 6.0.3 on 2026-07-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_purchase_order_received_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='labor_budget_hours',
            field=models.FloatField(blank=True, help_text='经理填写；已用工时由工单自动汇总', null=True, verbose_name='灌溉组预算工时'),
        ),
    ]
