# Generated by Django 6.0.3 on 2026-07-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_project_labor_verbose_rename'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['-date', '-id'], name='core_invtxn_date_id'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['related_project', 'operation'], name='core_invtxn_proj_op'),
        ),
        migrations.AddIndex(
            model_name='inventorytransactionline',
            index=models.Index(fields=['category'], name='core_invline_cat'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['-created_at'], name='core_po_created'),
        ),
        migrations.AddIndex(
            model_name='workreport',
            index=models.Index(fields=['worker', '-date'], name='core_wr_worker_date'),
        ),
        migrations.AddIndex(
            model_name='workreport',
            index=models.Index(fields=['zone_location', '-date'], name='core_wr_zone_date'),
        ),
    ]
