# Generated by Django 6.0.3 on 2026-07-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_inventorytransaction_core_invtxn_date_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='计划采购与已入库物料完全匹配后可标记完成；完成的订单仍可被项目引用', verbose_name='已完成'),
        ),
    ]
