# Generated by Django 6.0.3 on 2026-07-05 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_purchaseorder_is_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='waterrequest',
            name='submitter_user',
            field=models.ForeignKey(blank=True, help_text='提交需求的部门用户（Django User）。灌溉员提交走 submitter(Worker)。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='waterrequest',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.worker'),
        ),
    ]
