# Generated by Django 6.0.3 on 2026-07-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='labor_budget_hours',
        ),
        migrations.RemoveField(
            model_name='project',
            name='third_party_budget_hours',
        ),
        migrations.AddField(
            model_name='project',
            name='labor_budget_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='经理填写', max_digits=14, null=True, verbose_name='人工预算金额'),
        ),
        migrations.AddField(
            model_name='project',
            name='material_budget_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='经理填写；材料余额 = 材料预算 − Σ关联采购订单金额', max_digits=14, null=True, verbose_name='材料预算金额'),
        ),
        migrations.DeleteModel(
            name='ProjectMaterialBudget',
        ),
    ]
