# Generated by Django 6.0.3 on 2026-07-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_project_budget_amounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='元/小时；人工余额 = 人工预算 − 已用工时 × 费率', max_digits=14, null=True, verbose_name='灌溉组工时费率'),
        ),
        migrations.AddField(
            model_name='project',
            name='third_party_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='元/小时；人工余额 = 人工预算 − 已用工时 × 费率', max_digits=14, null=True, verbose_name='第三方工时费率'),
        ),
    ]
