# Generated by Django 5.2.15 on 2026-07-07 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_project_labor_rates'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransactionEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='编辑时间')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invtxn_edits', to='core.worker', verbose_name='编辑人')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='core.inventorytransaction', verbose_name='库存流水')),
            ],
            options={
                'verbose_name': '库存编辑记录',
                'verbose_name_plural': '库存编辑记录',
                'ordering': ['created_at'],
            },
        ),
    ]
