# Generated by Django 6.0.3 on 2026-07-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_inventorytransactioneditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='consumption_mode',
            field=models.CharField(choices=[('actual', '实际'), ('estimated', '预估')], default='actual', help_text='出库-项目时可选预估消耗，确认前不扣库存、不计入项目实际消耗', max_length=10, verbose_name='消耗类型'),
        ),
    ]
