# Generated by Django 6.0.3 on 2026-07-11 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_inventorytransaction_consumption_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='JobPlan名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('asset_level', models.CharField(choices=[('ccu', 'CCU级（每CCU一个工单）'), ('sat', 'SAT级（每SAT一个工单）'), ('zone_group', 'Zone组级（按通用位置分组）')], default='zone_group', max_length=20, verbose_name='资产粒度')),
                ('active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '作业计划模板',
                'verbose_name_plural': '作业计划模板',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='班组名称')),
                ('active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_crews', to='core.worker', verbose_name='组长')),
                ('members', models.ManyToManyField(blank=True, related_name='crews', to='core.worker', verbose_name='成员')),
                ('patches', models.ManyToManyField(blank=True, related_name='crews', to='core.patch', verbose_name='负责片区')),
            ],
            options={
                'verbose_name': '班组',
                'verbose_name_plural': '班组',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='如 "35-2"', max_length=20, unique=True, verbose_name='SAT编号')),
                ('name', models.CharField(blank=True, help_text='如 "探索路"', max_length=255, verbose_name='名称')),
                ('active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satellites', to='core.patch', verbose_name='所属CCU')),
            ],
            options={
                'verbose_name': 'SAT卫星控制器',
                'verbose_name_plural': 'SAT卫星控制器',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm_number', models.CharField(help_text='Maximo PM编号，如 "703605MJ1D"', max_length=50, unique=True, verbose_name='PM编号')),
                ('frequency_value', models.PositiveIntegerField(default=1, help_text='如 每2周 → 值=2', verbose_name='频率值')),
                ('frequency_unit', models.CharField(choices=[('days', '天'), ('weeks', '周'), ('months', '月')], default='weeks', max_length=10, verbose_name='频率单位')),
                ('start_date', models.DateField(help_text='基准日期（上次执行日），首次到期日从此开始算', verbose_name='启动日期')),
                ('lead_days', models.PositiveIntegerField(default=1, help_text='提前N天生成工单', verbose_name='提前生成天数')),
                ('active', models.BooleanField(default=True, verbose_name='启用')),
                ('last_generated_date', models.DateField(blank=True, null=True, verbose_name='上次生成日期')),
                ('remark_template', models.CharField(blank=True, help_text='生成工单时填入备注', max_length=255, verbose_name='工配备注模板')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_plans', to='core.crew', verbose_name='负责班组')),
                ('job_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='core.jobplantemplate', verbose_name='作业计划')),
                ('patch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_plans', to='core.patch', verbose_name='关联CCU')),
                ('zones', models.ManyToManyField(blank=True, related_name='pm_plans', to='core.zone', verbose_name='关联Zone组')),
                ('satellite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_plans', to='core.satellite', verbose_name='关联SAT')),
            ],
            options={
                'verbose_name': 'PM维护计划',
                'verbose_name_plural': 'PM维护计划',
                'ordering': ['pm_number'],
            },
        ),
        migrations.AddField(
            model_name='zone',
            name='satellite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones', to='core.satellite', verbose_name='所属SAT'),
        ),
        migrations.CreateModel(
            name='GeneratedWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='计划执行日期')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('dispatched', '已派发'), ('skipped', '跳过')], default='dispatched', max_length=20, verbose_name='状态')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('work_report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_generation', to='core.workreport', verbose_name='生成的工单')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_orders', to='core.maintenanceplan')),
            ],
            options={
                'verbose_name': 'PM派发记录',
                'verbose_name_plural': 'PM派发记录',
                'ordering': ['-scheduled_date'],
                'unique_together': {('plan', 'scheduled_date')},
            },
        ),
    ]
