# Generated by Django 6.0.3 on 2026-07-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_pm_system_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='patches',
        ),
        migrations.AddField(
            model_name='crew',
            name='lands',
            field=models.ManyToManyField(blank=True, related_name='crews', to='core.land', verbose_name='负责区域(Land)'),
        ),
    ]
