# Generated by Django 6.0.3 on 2026-07-11 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_crew_lands'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedworkorder',
            name='crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_orders', to='core.crew', verbose_name='派发班组'),
        ),
        migrations.AlterField(
            model_name='generatedworkorder',
            name='status',
            field=models.CharField(choices=[('pending', '待执行'), ('dispatched', '已派发'), ('completed', '已完成'), ('skipped', '跳过')], default='dispatched', max_length=20, verbose_name='状态'),
        ),
    ]
