# Generated by Django 6.0.3 on 2026-07-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_pm_work_item_leaf'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreport',
            name='ticket_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='工单编号'),
        ),
    ]
