# Generated by Django 6.0.3 on 2026-07-12 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_workreport_ticket_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedworkorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='generatedworkorder',
            name='status',
            field=models.CharField(choices=[('pending', '待执行'), ('dispatched', '已派发'), ('completed', '已完成'), ('overdue', '逾期'), ('skipped', '跳过')], default='dispatched', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='ExtensionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='延期理由')),
                ('requested_date', models.DateField(verbose_name='期望延期到')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审批状态')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('review_note', models.TextField(blank=True, verbose_name='审批备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to='core.generatedworkorder', verbose_name='关联工单')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_extension_requests', to='core.worker', verbose_name='申请人')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_pm_extensions', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
            ],
            options={
                'verbose_name': '延期申请',
                'verbose_name_plural': '延期申请',
                'ordering': ['-created_at'],
            },
        ),
    ]
