# Generated by Django 5.2.13 on 2026-07-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_zone_maxicom_runtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceplan',
            name='lead_days',
            field=models.PositiveIntegerField(default=28, help_text='提前N天生成工单', verbose_name='提前生成天数'),
        ),
    ]
