# Generated by Django 4.2.29 on 2026-07-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_alter_maintenanceplan_lead_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='patches',
            field=models.ManyToManyField(blank=True, help_text='班组负责的CCU。CCU/SAT级PM优先按CCU匹配班组，Land级仍按负责区域匹配。', limit_choices_to={'code__regex': '^CCU[0-9]+$'}, related_name='crews', to='core.patch', verbose_name='负责CCU'),
        ),
    ]
