# Generated by Django 4.2.29 on 2026-07-23 14:28

from django.db import migrations, models
import django.db.models.deletion


def _backfill_pm_fields(apps, schema_editor):
    """Mark existing PM-linked reports is_pm=True and seed GWO.zones/remark.

    GWO.zones is derived the same way the dispatch engine resolves zones
    (zone_group→plan.zones, ccu→plan.patch.zones, sat→plan.satellite.zones).
    """
    WorkReport = apps.get_model('core', 'WorkReport')
    GeneratedWorkOrder = apps.get_model('core', 'GeneratedWorkOrder')
    MaintenancePlan = apps.get_model('core', 'MaintenancePlan')

    # (a) Any WorkReport still linked to a GWO is a PM report.
    WorkReport.objects.filter(pm_generation__isnull=False).update(is_pm=True)

    # (b) Populate GWO.zones + remark from each GWO's plan.
    plans_by_id = {p.id: p for p in MaintenancePlan.objects.all()}
    for gwo in GeneratedWorkOrder.objects.select_related('plan', 'plan__job_plan'):
        if gwo.zones.exists() or gwo.remark:
            continue
        plan = gwo.plan
        level = plan.job_plan.asset_level if plan.job_plan_id else None
        zone_ids = set()
        if level == 'zone_group':
            zone_ids = set(plan.zones.values_list('id', flat=True))
        elif level == 'sat' and plan.satellite_id:
            zone_ids = set(plan.satellite.zones.values_list('id', flat=True))
        elif level == 'ccu' and plan.patch_id:
            zone_ids = set(plan.patch.zones.values_list('id', flat=True))
        if zone_ids:
            gwo.zones.set(zone_ids)
        if not gwo.remark:
            remark = plan.remark_template or (
                f'{plan.job_plan.name} - {plan.pm_number}' if plan.job_plan_id else plan.pm_number)
            gwo.remark = remark
            gwo.save(update_fields=['remark'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_crew_patches'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedworkorder',
            name='remark',
            field=models.TextField(blank=True, default='', verbose_name='备注快照'),
        ),
        migrations.AddField(
            model_name='generatedworkorder',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_orders', to='core.worker', verbose_name='指派工人'),
        ),
        migrations.AddField(
            model_name='generatedworkorder',
            name='zones',
            field=models.ManyToManyField(blank=True, help_text='派发时快照的目标Zone（完成时用于填充工单区域）。', related_name='pm_orders', to='core.zone', verbose_name='关联Zone'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='is_pm',
            field=models.BooleanField(db_index=True, default=False, verbose_name='PM生成工单'),
        ),
        # Backfill: mark existing PM-linked WorkReports as is_pm (so the 维修日志
        # isolation applies retroactively), and populate GWO.zones from each GWO's
        # plan so the PM tab can render without a WorkReport shell.
        migrations.RunPython(_backfill_pm_fields, migrations.RunPython.noop),
    ]
