# Generated by Django 4.2.29 on 2026-07-23 15:31

from django.db import migrations, models
import django.db.models.deletion


def _migrate_pm_reports(apps, schema_editor):
    """Move is_pm=True WorkReports into the new PMWorkOrder table.

    For each: create a PMWorkOrder mirroring its fields, repoint its child
    rows (entries, material txns, edit logs) to pm_work_order, link the GWO's
    pm_order, then delete the shell WorkReport (its id is freed).
    """
    WorkReport = apps.get_model('core', 'WorkReport')
    PMWorkOrder = apps.get_model('core', 'PMWorkOrder')
    WorkReportEntry = apps.get_model('core', 'WorkReportEntry')
    InventoryTransaction = apps.get_model('core', 'InventoryTransaction')
    WorkReportEditLog = apps.get_model('core', 'WorkReportEditLog')
    GeneratedWorkOrder = apps.get_model('core', 'GeneratedWorkOrder')

    for wr in WorkReport.objects.filter(is_pm=True):
        # Resolve the linked GWO (via the old work_report OneToOne reverse).
        gwo = None
        try:
            gwo = GeneratedWorkOrder.objects.get(work_report=wr)
        except GeneratedWorkOrder.DoesNotExist:
            pass
        if not gwo:
            continue  # orphaned PM report with no GWO — skip
        pmwo = PMWorkOrder.objects.create(
            gwo=gwo,
            worker_id=wr.worker_id,
            location_id=wr.location_id,
            zone_location_id=wr.zone_location_id,
            date=wr.date,
            remark=wr.remark or '',
            shift=wr.shift or '',
            work_start_time=wr.work_start_time,
            work_end_time=wr.work_end_time,
            team_size=wr.team_size,
            third_party_count=wr.third_party_count,
            team_hours=wr.team_hours,
            third_party_hours=wr.third_party_hours,
            zone_names=wr.zone_names or '',
            photos=wr.photos or [],
        )
        # Repoint M2M zones.
        pmwo.zones.set(wr.zones.all())
        # Repoint child rows.
        WorkReportEntry.objects.filter(work_report=wr).update(work_report=None, pm_work_order=pmwo)
        InventoryTransaction.objects.filter(work_report=wr).update(work_report=None, pm_work_order=pmwo)
        WorkReportEditLog.objects.filter(work_report=wr).update(work_report=None, pm_work_order=pmwo)
        # Link GWO → PMWorkOrder.
        gwo.pm_order = pmwo
        gwo.save(update_fields=['pm_order'])
        # Drop the shell WorkReport (its id slot is now free for normal use).
        wr.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_generatedworkorder_remark_generatedworkorder_worker_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workreportentry',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='generatedworkorder',
            name='work_report',
            field=models.OneToOneField(blank=True, help_text='已弃用 — PM 完成数据现在存 PMWorkOrder，经 pm_order 关联。保留仅为迁移兼容。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_generation', to='core.workreport', verbose_name='生成的工单(旧)'),
        ),
        migrations.AlterField(
            model_name='workreporteditlog',
            name='work_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='core.workreport', verbose_name='工单'),
        ),
        migrations.AlterField(
            model_name='workreportentry',
            name='work_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.workreport', verbose_name='工单'),
        ),
        migrations.CreateModel(
            name='PMWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='日期')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('shift', models.CharField(blank=True, choices=[('早班', '早班'), ('白班', '白班'), ('夜班', '夜班')], max_length=10, verbose_name='班次')),
                ('work_start_time', models.TimeField(blank=True, null=True, verbose_name='工作开始时间')),
                ('work_end_time', models.TimeField(blank=True, null=True, verbose_name='工作完成时间')),
                ('team_size', models.PositiveIntegerField(default=1, verbose_name='灌溉组人数')),
                ('third_party_count', models.PositiveIntegerField(default=0, verbose_name='第三方人数')),
                ('team_hours', models.FloatField(default=0, verbose_name='灌溉组工时')),
                ('third_party_hours', models.FloatField(default=0, verbose_name='第三方工时')),
                ('zone_names', models.TextField(blank=True, verbose_name='通称位置')),
                ('photos', models.JSONField(blank=True, default=list, verbose_name='照片列表')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gwo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.generatedworkorder', verbose_name='关联派发工单')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pm_work_orders', to='core.patch', verbose_name='位置/CCU')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pm_work_orders', to='core.worker', verbose_name='处理人')),
                ('zone_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_work_orders', to='core.zone', verbose_name='位置区域')),
                ('zones', models.ManyToManyField(blank=True, related_name='pm_workorder_records', to='core.zone', verbose_name='区域')),
            ],
            options={
                'verbose_name': 'PM完成工单',
                'verbose_name_plural': 'PM完成工单',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='generatedworkorder',
            name='pm_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.pmworkorder', verbose_name='PM完成工单'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='pm_work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_consumptions', to='core.pmworkorder', verbose_name='关联PM工单'),
        ),
        migrations.AddField(
            model_name='workreporteditlog',
            name='pm_work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='core.pmworkorder', verbose_name='PM工单'),
        ),
        migrations.AddField(
            model_name='workreportentry',
            name='pm_work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.pmworkorder', verbose_name='PM工单'),
        ),
        migrations.RunPython(_migrate_pm_reports, migrations.RunPython.noop),
    ]
