# Generated by Django 4.2.29 on 2026-07-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_workreport_followup_collab'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreport',
            name='followup_action',
            field=models.CharField(blank=True, default='', help_text='子工单提交时的动作：ongoing(继续跟进)/fixed(已修复)；仅跟进子工单有意义', max_length=10, verbose_name='跟进动作'),
        ),
    ]
