# Generated by Django 4.2.29 on 2026-08-12 14:40
# Adds main_diameter / flow_direction / source_label to Pipeline, creates the
# PipeValve bridge model, and back-fills Pipeline.zones from geometry for any
# pre-existing rows (currently 0) via pipe_utils.detect_crossed_zones.

from django.db import migrations, models
import django.db.models.deletion


def populate_pipeline_zones_from_geometry(apps, schema_editor):
    """For each existing Pipeline, auto-derive crossed zones from line_points
    and merge into Pipeline.zones. No-op when no pipelines exist yet (forward-
    compatible: future pipelines get this treatment at save-time in the view)."""
    Pipeline = apps.get_model('core', 'Pipeline')
    Zone = apps.get_model('core', 'Zone')
    # Import pipe_utils lazily; it imports models at call time via apps registry
    # is not used here (it does `from .models import Zone`) — so call the pure
    # helpers directly to stay within the migration's app registry.
    from core.pipe_utils import flatten_rings, _point_in_ring, _segments_intersect, _to_latlng, _bboxes_overlap, _ring_bbox

    def _active_pts(z):
        # Replicates Zone.active_boundary_points property (not on historical model).
        if getattr(z, 'boundary_source', None) == 'dxf' and z.dxf_boundary_points:
            return z.dxf_boundary_points
        return z.boundary_points or []

    zones = list(Zone.objects.exclude(boundary_points=[]).only(
        'id', 'boundary_points', 'dxf_boundary_points', 'boundary_source'))
    # Pre-flatten rings once.
    zone_rings = []
    for z in zones:
        rings = flatten_rings(_active_pts(z))
        if rings:
            bboxes = [_ring_bbox(r) for r in rings]
            zone_rings.append((z.id, rings, bboxes))

    for p in Pipeline.objects.all():
        line = [_to_latlng(pt) for pt in (p.line_points or [])]
        line = [pt for pt in line if pt]
        if len(line) < 2:
            continue
        lats = [pt[0] for pt in line]
        lngs = [pt[1] for pt in line]
        buf = 20.0 / 111000.0
        line_bbox = (min(lats) - buf, max(lats) + buf, min(lngs) - buf, max(lngs) + buf)
        line_segs = list(zip(line[:-1], line[1:]))

        hit_ids = []
        for zid, rings, bboxes in zone_rings:
            hit = False
            for ring, r_bbox in zip(rings, bboxes):
                if not _bboxes_overlap(line_bbox, r_bbox):
                    continue
                for (lat, lng) in line:
                    if _point_in_ring(lat, lng, ring):
                        hit = True
                        break
                if hit:
                    break
                n = len(ring)
                for s_a, s_b in line_segs:
                    for i in range(n):
                        if _segments_intersect(s_a, s_b, ring[i], ring[(i + 1) % n]):
                            hit = True
                            break
                    if hit:
                        break
                if hit:
                    break
            if hit:
                hit_ids.append(zid)
        if hit_ids:
            existing = set(p.zones.values_list('id', flat=True))
            to_add = [zid for zid in hit_ids if zid not in existing]
            if to_add:
                p.zones.add(*to_add)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_workreport_hours_materials_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='flow_direction',
            field=models.CharField(choices=[('fwd', '正向(点序)'), ('rev', '反向'), ('none', '未定')], default='fwd', help_text='相对 line_points[0]→[N] 的方向，决定地图箭头朝向', max_length=4, verbose_name='水流方向'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='main_diameter',
            field=models.FloatField(blank=True, help_text='整条主管的公称直径，用于地图线宽映射。支管变径在阀门上记口径。', null=True, verbose_name='主管径(mm)'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='source_label',
            field=models.CharField(blank=True, help_text='如：接市政水 DN80 / 接 CCU1 主泵', max_length=100, verbose_name='水源/起点'),
        ),
        migrations.CreateModel(
            name='PipeValve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='阀门编号/名称')),
                ('point', models.JSONField(blank=True, default=list, help_text='[{lat,lng}] 在管道上的位置(单点)')),
                ('valve_type', models.CharField(choices=[('solenoid', '电磁阀'), ('isolation', '隔离阀'), ('flush', '冲洗阀')], default='solenoid', max_length=20, verbose_name='阀门类型')),
                ('diameter', models.FloatField(blank=True, null=True, verbose_name='口径(mm)')),
                ('order', models.IntegerField(default=0, help_text='从水源起的序号，用于沿线排序', verbose_name='沿线顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valves', to='core.pipeline', verbose_name='所属管道')),
                ('station', models.ForeignKey(blank=True, help_text='对应的 Maxicom station Patch(物理电磁阀)，用于反查灌溉时长', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipe_valves', to='core.patch', verbose_name='Maxicom station')),
                ('zone', models.ForeignKey(blank=True, help_text='该阀门浇水/控制的灌溉区域', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipe_valves', to='core.zone', verbose_name='控制区域')),
            ],
            options={
                'verbose_name': '管道阀门',
                'verbose_name_plural': '管道阀门',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(
            populate_pipeline_zones_from_geometry,
            reverse_code=noop_reverse,
        ),
    ]
