# Generated by Django 4.2.29 on 2026-08-14 05:01
# Adds confirm_status (manager ledger confirmation) to InventoryTransaction and
# grandfathers all existing rows as 'confirmed' so current behavior is unchanged —
# only new frontline submissions start in 'pending' awaiting manager confirmation.

from django.db import migrations, models


def grandfather_existing_confirmed(apps, schema_editor):
    InventoryTransaction = apps.get_model('core', 'InventoryTransaction')
    InventoryTransaction.objects.filter(confirm_status='pending').update(confirm_status='confirmed')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_pipeline_valves_diameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='confirm_status',
            field=models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('removed', '已移除')], db_index=True, default='pending', help_text='经理台账确认：待确认/已移除不计入物料出入库统计（库存仍正常扣减）', max_length=10, verbose_name='确认状态'),
        ),
        migrations.RunPython(grandfather_existing_confirmed, reverse_code=noop_reverse),
    ]
