# Generated by Django 5.2.13 on 2026-09-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_sitecalibration_applied_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='maxicomruntime',
            new_name='core_maxico_station_fb13ae_idx',
            old_name='core_mr_station_ts',
        ),
        migrations.AddField(
            model_name='sitecalibration',
            name='method',
            field=models.CharField(blank=True, default='', help_text="''=按点数自动(tps/similarity) / 'tps'=薄板样条 / 'mls'=移动最小二乘(边界稳定)", max_length=12, verbose_name='拟合方法'),
        ),
        migrations.AlterField(
            model_name='inventorycategory',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='inventorycategory',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='inventorycategory',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='inventorycategory',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='inventorypricerecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='confirm_status',
            field=models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('removed', '已移除')], db_index=True, default='pending', help_text='经理台账确认：确认后才扣减库存并计入物料出入库统计', max_length=10, verbose_name='确认状态'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='flow_direction',
            field=models.CharField(choices=[('fwd', '正向(点序)'), ('rev', '反向'), ('none', '未定')], default='fwd', help_text='相对 line_points[0]→[N] 的方向（地图方向箭头已移除，仅作数据记录）', max_length=4, verbose_name='水流方向'),
        ),
        migrations.AlterField(
            model_name='pipelineimportbatch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitecalibration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
