# Generated by Django 4.2.29 on 2026-09-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_rename_core_mr_station_ts_core_maxico_station_fb13ae_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecalibration',
            name='method',
            field=models.CharField(blank=True, default='', help_text="''=按点数自动(tps/similarity) / 'sim'=相似变换(强制) / 'tps'=薄板样条 / 'mls'=移动最小二乘(边界稳定)", max_length=12, verbose_name='拟合方法'),
        ),
    ]
