# Generated by Django 5.2.13 on 2026-09-12 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_alter_sitecalibration_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxicomStationFlowFactor',
            fields=[
                ('station_raw', models.IntegerField(primary_key=True, serialize=False, verbose_name='STATN_CF IndexNumber')),
                ('factor', models.FloatField(default=0, verbose_name='流量系数 L/min')),
            ],
            options={
                'verbose_name': 'Maxicom站点流量系数',
                'verbose_name_plural': 'Maxicom站点流量系数',
            },
        ),
        migrations.CreateModel(
            name='MaxicomFlowDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_day', models.CharField(db_index=True, max_length=8, verbose_name='灌溉日 YYYYMMDD')),
                ('liters', models.IntegerField(verbose_name='浇水量(升)')),
                ('minutes', models.IntegerField(default=0, verbose_name='有流量的分钟数')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_daily', to='core.patch', verbose_name='CCU')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily', to='core.maxicomflowzone')),
            ],
            options={
                'verbose_name': 'Maxicom浇水量(日)',
                'verbose_name_plural': 'Maxicom浇水量(日)',
                'indexes': [models.Index(fields=['site', 'flow_day'], name='core_maxico_site_id_3563b2_idx')],
                'constraints': [models.UniqueConstraint(fields=('flow_day', 'zone'), name='uniq_flow_day_zone')],
            },
        ),
    ]
