from django.urls import path, include
from rest_framework.routers import DefaultRouter
from core import views
from core.sync_views import sync_receive, sync_status, agent_status
from core.ai_views import ai_chat, ai_status
from core.api import (
    ZoneViewSet, PlantViewSet, WorkerViewSet,
    WaterRequestViewSet,
    EquipmentCatalogViewSet, ZoneEquipmentViewSet,
    PipelineViewSet,
    PatchViewSet, LocationViewSet, RegionViewSet,
    WorkReportViewSet,
    worker_login, get_weather,
)
from core.views import equipment_catalog_autocomplete
from core.workorder_tree_views import (
    workorder_tree_form, project_create_api, planned_maintenance_pending,
    project_management, project_save, project_delete,
    project_budget_save, project_pos_save, project_export_excel,
)

app_name = 'core'

router = DefaultRouter()
router.register(r'zones', ZoneViewSet)
router.register(r'plants', PlantViewSet)
router.register(r'workers', WorkerViewSet)
router.register(r'water-requests', WaterRequestViewSet)
router.register(r'equipment-catalog', EquipmentCatalogViewSet)
router.register(r'zone-equipment', ZoneEquipmentViewSet)
router.register(r'pipelines', PipelineViewSet)
router.register(r'patches', PatchViewSet)
router.register(r'regions', RegionViewSet)
router.register(r'locations', LocationViewSet, basename='location')
router.register(r'work-reports', WorkReportViewSet, basename='workreport')

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('stats/', views.stats_dashboard, name='stats_dashboard'),
    path('stats/excel/', views.work_reports_excel, name='work_reports_excel'),
    path('irrigation/', views.irrigation_dashboard, name='irrigation_dashboard'),
    path('api/stats/zone-heatmap/', views.stats_zone_heatmap, name='stats_zone_heatmap'),
    path('irrigation/report.pdf', views.irrigation_report_pdf, name='irrigation_report_pdf'),
    path('irrigation/report.xlsx', views.irrigation_report_excel, name='irrigation_report_excel'),
    path('login/', views.user_login, name='login'),

    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.profile_page, name='profile'),
    path('register/', views.register, name='register'),
    path('registration-approval/', views.registration_approval, name='registration_approval'),
    path('user-management/', views.user_management, name='user_management'),
    path('user-management/<str:profile_type>/<int:profile_id>/edit/', views.user_edit, name='user_edit'),
    path('settings/', views.settings_page, name='settings'),
    path('settings/zone/export/', views.zone_export_excel, name='zone_export_excel'),
    path('settings/zone/import/', views.zone_import_preview, name='zone_import_preview'),
    path('settings/zone/import/confirm/', views.zone_import_confirm, name='zone_import_confirm'),
    path('settings/zone/<int:zone_id>/', views.zone_edit, name='zone_edit'),
    path('zone/<int:zone_id>/detail/', views.zone_detail_page, name='zone_detail'),
    path('zone/<int:zone_id>/smooth/', views.zone_smooth_update, name='zone_smooth_update'),
    path('zone/<int:zone_id>/remark/add/', views.zone_remark_add, name='zone_remark_add'),
    path('zone/<int:zone_id>/remark/<int:index>/confirm/', views.zone_remark_confirm, name='zone_remark_confirm'),
    path('zone/<int:zone_id>/remark/<int:index>/move/', views.zone_remark_move, name='zone_remark_move'),
    path('zone/<int:zone_id>/remark/<int:index>/archive/', views.zone_remark_archive, name='zone_remark_archive'),
    path('settings/zone/<int:zone_id>/delete/', views.zone_delete, name='zone_delete'),
    path('settings/zone/new/', views.zone_new, name='zone_new'),
    path('settings/zone/batch-draw/', views.zone_batch_draw, name='zone_batch_draw'),
    path('settings/zone/quick-draw/', views.zone_quick_draw, name='zone_quick_draw'),
    path('settings/zone/quick-draw/mobile/', views.zone_quick_draw_mobile, name='zone_quick_draw_mobile'),
    path('settings/zone/dxf-import/', views.zone_dxf_import, name='zone_dxf_import'),
    path('settings/map-style/', views.map_style_editor, name='map_style_editor'),
    path('settings/pipeline/new/', views.pipeline_new, name='pipeline_new'),
    path('settings/pipeline/<int:pipeline_id>/', views.pipeline_edit, name='pipeline_edit'),
    path('settings/pipeline/<int:pipeline_id>/delete/', views.pipeline_delete, name='pipeline_delete'),
    path('settings/patch/new/', views.patch_new, name='patch_new'),
    path('settings/patch/<int:patch_id>/', views.patch_edit, name='patch_edit'),
    path('settings/patch/<int:patch_id>/delete/', views.patch_delete, name='patch_delete'),
    path('settings/batch-delete-patch/', views.batch_delete_patch, name='batch_delete_patch'),
    path('settings/batch-delete-zone/', views.batch_delete_zone, name='batch_delete_zone'),
    path('settings/batch-delete-pipeline/', views.batch_delete_pipeline, name='batch_delete_pipeline'),
    path('settings/region/new/', views.region_new, name='region_new'),
    path('settings/region/<int:region_id>/', views.region_edit, name='region_edit'),
    path('settings/region/<int:region_id>/delete/', views.region_delete, name='region_delete'),
    path('settings/batch-delete-region/', views.batch_delete_region, name='batch_delete_region'),
    path('settings/landmark/new/', views.landmark_new, name='landmark_new'),
    path('settings/landmark/<int:landmark_id>/', views.landmark_edit, name='landmark_edit'),
    path('settings/landmark/<int:landmark_id>/delete/', views.landmark_delete, name='landmark_delete'),
    path('settings/batch-delete-landmark/', views.batch_delete_landmark, name='batch_delete_landmark'),
    path('api/landmarks/', views.landmarks_api, name='landmarks_api'),
    path('api/landmarks/recalculate/', views.landmarks_recalculate, name='landmarks_recalculate'),
    path('work-reports/', views.work_reports_list, name='work_reports'),
    path('work-reports/photos/', views.work_report_photos, name='work_report_photos'),
    path('work-reports/photos/download/', views.work_report_photos_download, name='work_report_photos_download'),
    path('requests/', views.water_requests_list, name='water_requests'),
    path('requests/<int:pk>/update/', views.water_request_update, name='water_request_update'),
    path('requests/<int:pk>/resubmit/', views.water_request_resubmit, name='water_request_resubmit'),
    path('api/notifications/<int:nid>/read/', views.notification_read, name='notification_read'),
    path('remarks/', views.remarks_list, name='remarks'),
    path('work-reports/new/', views.work_report_create, name='work_report_create'),
    path('work-reports/tree/new/', workorder_tree_form, name='workorder_tree_form'),
    path('api/irrigation-project/create/', project_create_api, name='irrigation_project_create'),
    path('api/planned-maintenance/pending/', planned_maintenance_pending, name='planned_maintenance_pending'),
    path('projects/', project_management, name='project_management'),
    path('projects/export/', project_export_excel, name='project_export_excel'),
    path('projects/save/', project_save, name='project_save'),
    path('projects/<int:pk>/delete/', project_delete, name='project_delete'),
    path('projects/<int:pk>/budget/save/', project_budget_save, name='project_budget_save'),
    path('projects/<int:pk>/pos/save/', project_pos_save, name='project_pos_save'),
    path('inventory/manage/', views.inventory_management, name='inventory_management'),
    path('inventory/manage/category/<int:cat_id>/transactions/', views.inventory_category_transactions, name='inventory_category_transactions'),
    path('inventory/save-stock/', views.inventory_save_stock, name='inventory_save_stock'),
    path('inventory/export-excel/', views.inventory_export_excel, name='inventory_export_excel'),
    path('inventory/export-transactions/', views.inventory_transactions_export, name='inventory_transactions_export'),
    path('inventory/category/create/', views.inventory_category_create, name='inventory_category_create'),
    path('inventory/category/<int:cat_id>/delete/', views.inventory_category_delete, name='inventory_category_delete'),
    path('inventory/category/<int:cat_id>/edit/', views.inventory_category_edit, name='inventory_category_edit'),
    path('inventory/estimate/<int:txn_id>/confirm/', views.inventory_estimate_confirm, name='inventory_estimate_confirm'),
    path('inventory/estimate/<int:txn_id>/void/', views.inventory_estimate_void, name='inventory_estimate_void'),
    path('purchase-orders/create/', views.purchase_order_create, name='purchase_order_create'),
    path('purchase-orders/export/', views.purchase_order_export_excel, name='purchase_order_export_excel'),
    path('purchase-orders/<int:po_id>/edit/', views.purchase_order_edit, name='purchase_order_edit'),
    path('purchase-orders/<int:po_id>/delete/', views.purchase_order_delete, name='purchase_order_delete'),
    path('purchase-orders/<int:po_id>/complete/', views.purchase_order_complete, name='purchase_order_complete'),
    path('announcements/save/', views.announcement_save, name='announcement_save'),
    path('announcements/<int:pk>/delete/', views.announcement_delete, name='announcement_delete'),
    path('api/announcements/<int:pk>/acknowledge/', views.announcement_acknowledge, name='announcement_acknowledge'),
    path('api/announcements/<int:pk>/unacked/', views.announcement_unacked_api, name='announcement_unacked_api'),
    path('work-reports/tree/<int:report_id>/edit/', workorder_tree_form, name='workorder_tree_form_edit'),
    path('work-reports/<int:report_id>/', views.work_report_detail, name='work_report_detail'),
    path('work-reports/<int:report_id>/edit/', views.work_report_edit, name='work_report_edit'),
    path('work-reports/<int:report_id>/upload-photo/', views.work_report_upload_photo, name='work_report_upload_photo'),
    path('work-reports/<int:report_id>/remove-photo/', views.work_report_remove_photo, name='work_report_remove_photo'),
    path('work-reports/<int:report_id>/delete/', views.work_report_delete, name='work_report_delete'),
    path('work-reports/<int:report_id>/comments/', views.work_report_comments, name='work_report_comments'),
    path('work-reports/<int:report_id>/reassign/', views.work_report_reassign, name='work_report_reassign'),
    path('mobile/workorder/v2/', views.workorder_mobile_v2, name='workorder_mobile_v2'),
    path('mobile/water-request/v2/', views.water_request_mobile_v2, name='water_request_mobile_v2'),
    path('mobile/inventory/v2/', views.inventory_mobile_v2, name='inventory_mobile_v2'),
    path('api/zone-geo/', views.zone_geo_api, name='zone_geo_api'),
    path('api/zones-payload/', views.zones_payload_api, name='zones_payload_api'),
    path('api/today-weather/', views.today_weather_api, name='today_weather_api'),
    path('api/zones-in-area/', views.zones_in_area_api, name='zones_in_area_api'),
    path('api/modal/workorder-data/', views.workorder_modal_data, name='workorder_modal_data'),
    path('api/modal/water-request-data/', views.water_request_modal_data, name='water_request_modal_data'),
    path('api/modal/inventory-data/', views.inventory_modal_data, name='inventory_modal_data'),
    path('api/auth/login', worker_login, name='worker_login'),
    path('api/weather', get_weather, name='get_weather'),
    path('api/custom-report', views.custom_report_api, name='custom_report_api'),
    path('custom-report/', views.custom_report, name='custom_report'),
    path('api/equipment-catalog/autocomplete', equipment_catalog_autocomplete, name='equipment_catalog_autocomplete'),
    path('api/zones-by-patch/', views.zone_batch_draw_zones_api, name='zones_by_patch'),
    path('api/', include(router.urls)),
    path('api/user/preferences', views.user_preferences_api, name='user_preferences_api'),
    path('api/maxicom-dashboard', views.maxicom_dashboard_api, name='maxicom_dashboard_api'),
    path('api/sync/receive', sync_receive, name='sync_receive'),
    path('api/sync/status', sync_status, name='sync_status'),
    path('api/sync/agent-status', agent_status, name='agent_status'),
    path('api/ai/chat', ai_chat, name='ai_chat'),
    path('api/ai/status', ai_status, name='ai_status'),
]
